"use client"
import { useState } from "react"
import { ArrowDownRight,ArrowUpRight,ArrowLeftRight,Bell,Check,Gauge as GaugeIcon,History,Scale,Search,ShieldAlert,ShieldCheck,Undo2,X } from "lucide-react"
import type { NegotiationView,Outcome,Verdict } from "@/lib/types"
import { Gauge,HistoryChart,MaturityRadar } from "./dashboard-charts"
import { priorityOf } from "@/lib/health"
import { useGovernance } from "./governance-provider"
import { Card,CardContent,CardDescription,CardHeader,CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Progress } from "@/components/ui/progress"
import { Select,SelectContent,SelectGroup,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select"
import { Sheet,SheetContent,SheetDescription,SheetHeader,SheetTitle } from "@/components/ui/sheet"
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from "@/components/ui/table"

export function CommandCenter(){const {domains,objectives,pending,notices,log,saving,decide,undo,deltaFor,healthOf,domainHealthOf,coverage}=useGovernance();const [query,setQuery]=useState("");const [domain,setDomain]=useState("ALL");const [selectedCode,setSelectedCode]=useState<string|null>(null);
const scored=objectives.map(o=>{const delta=deltaFor(o.code);const score=healthOf(o);return {...o,score,delta,priority:priorityOf(score)}});
const filtered=scored.filter(o=>(domain==="ALL"||o.domain===domain)&&(o.code+o.name).toLowerCase().includes(query.toLowerCase()));
const selected=scored.find(o=>o.code===selectedCode)??null;const selectedDecision=log.find(r=>r.objective===selectedCode)??null;
return <div className="flex flex-col gap-6">
<section className="grid gap-4 sm:grid-cols-2 md:grid-cols-5">{domains.map(d=>{const {score,fromDecisions:delta}=domainHealthOf(d.code);return <Card key={d.code} className={`overflow-hidden transition-colors ${score===null?"":score<70?"critical-glow":score<80?"warning-glow":""}`}><CardHeader className="pb-0"><div className="flex items-center justify-between"><Badge variant="outline" className="font-mono">{d.code}</Badge>{d.trend!==null?<span className={`flex items-center text-xs ${d.trend>0?"text-success":"text-destructive"}`}>{d.trend>0?<ArrowUpRight/>:<ArrowDownRight/>}{Math.abs(d.trend)}%</span>:<span className="text-xs text-muted-foreground">sin historial</span>}</div><CardDescription className="min-h-10 text-xs leading-relaxed">{d.name}</CardDescription></CardHeader><CardContent className="flex flex-col items-center">{score===null?<div className="flex size-28 flex-col items-center justify-center rounded-full border border-dashed text-center"><span className="font-mono text-2xl text-muted-foreground">—</span><span className="status-label mt-0.5 text-[9px] text-muted-foreground">sin dato</span></div>:<Gauge value={score} label={d.code}/>}{delta!==0&&<span className={`mt-1 font-mono text-[10px] ${delta>0?"text-success":"text-destructive"}`}>{delta>0?"+":""}{delta} por tus decisiones</span>}</CardContent></Card>})}</section>
<div className="flex flex-wrap items-center gap-x-4 gap-y-1 rounded-lg border bg-background/40 px-4 py-2 text-xs"><span className="flex items-center gap-1.5 font-medium"><GaugeIcon className="size-3.5 text-primary"/>Cobertura de medición</span><span className="font-mono text-primary">{coverage.covered} de {coverage.total} objetivos</span><span className="text-muted-foreground">se derivan de evidencia operativa (incidentes, cambios, riesgos, pruebas de control). El resto muestra su línea base y así se marca en la tabla.</span></div>

<Card className={pending.length>0?"border-primary/30":undefined}><CardHeader><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><CardTitle>Decisiones pendientes</CardTitle><CardDescription>Negociaciones que los agentes no pudieron cerrar dentro del mandato vigente. Requieren tu firma.</CardDescription></div><Badge variant={pending.length>0?"destructive":"secondary"}>{pending.length} en espera</Badge></div></CardHeader><CardContent>{pending.length===0?<div className="flex flex-col items-center gap-2 rounded-lg border border-dashed py-12 text-center"><ShieldCheck className="size-6 text-success"/><p className="text-sm font-medium">No hay decisiones pendientes</p><p className="max-w-md text-xs leading-relaxed text-muted-foreground">Todas las discrepancias se resolvieron entre agentes aplicando el mandato que fijaste. Solo escalan las que exigirían cambiarlo.</p></div>:<div className="grid gap-4 xl:grid-cols-2">{pending.map(n=><DecisionCard key={n.id} negotiation={n} saving={saving} onDecide={decide}/>)}</div>}</CardContent></Card>

<section className="grid gap-4 xl:grid-cols-[minmax(0,1.65fr)_minmax(300px,.75fr)]"><Card><CardHeader><div className="flex items-end justify-between"><div><CardTitle>Madurez por dominio</CardTitle><CardDescription>Capacidad actual vs. objetivo · escala COBIT 0-5</CardDescription></div><div className="hidden gap-4 text-xs sm:flex"><span className="text-primary">● Actual</span><span className="text-muted-foreground">● Objetivo</span></div></div></CardHeader><CardContent className="h-80"><MaturityRadar data={domains.map(d=>{const s=domainHealthOf(d.code).score;return {d:d.code,actual:s===null?0:Math.round(s/2)/10,target:d.targetMaturity}})}/></CardContent></Card><Card><CardHeader><div className="flex items-center justify-between"><div><CardTitle>Avisos de los agentes</CardTitle><CardDescription>{notices.length} señales que no requieren decisión</CardDescription></div><Bell className="text-warning"/></div></CardHeader><CardContent className="flex max-h-80 flex-col gap-2 overflow-y-auto">{notices.map(n=><article key={n.id} className="rounded-lg border bg-background/50 p-4"><div className="flex items-center gap-2"><Badge variant="outline" className="font-mono">{n.objective}</Badge><span className="ml-auto text-xs text-muted-foreground">{n.time}</span></div><p className="mt-2 text-sm leading-relaxed">{n.fact}</p><p className="mt-1 text-xs text-muted-foreground">{n.agent}</p></article>)}</CardContent></Card></section>

{log.length>0&&<Card><CardHeader><div className="flex items-center justify-between"><div><CardTitle>Registro de decisiones</CardTitle><CardDescription>Trazabilidad de gobierno · {log.length} {log.length===1?"decisión registrada":"decisiones registradas"} en base de datos</CardDescription></div><History className="text-muted-foreground"/></div></CardHeader><CardContent className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Hora</TableHead><TableHead>Objetivo</TableHead><TableHead>Decisión</TableHead><TableHead>Qué queda registrado</TableHead><TableHead>Responsable</TableHead><TableHead>Efecto</TableHead><TableHead className="text-right">Revertir</TableHead></TableRow></TableHeader><TableBody>{log.map(r=><TableRow key={r.negotiationId}><TableCell className="font-mono text-xs text-muted-foreground">{r.at}</TableCell><TableCell className="font-mono text-primary">{r.objective}</TableCell><TableCell><Badge variant={r.verdict==="approved"?"secondary":"destructive"}>{r.verdict==="approved"?"Aprobada":"Rechazada"}</Badge></TableCell><TableCell className="min-w-80"><p className="font-medium">{r.label}</p><p className="text-xs leading-relaxed text-muted-foreground">{r.impact}</p></TableCell><TableCell className="text-xs text-muted-foreground">{r.decidedBy}</TableCell><TableCell className={`font-mono ${r.delta>0?"text-success":r.delta<0?"text-destructive":"text-muted-foreground"}`}>{r.delta===0?"vía operación":`${r.delta>0?"+":""}${r.delta}`}</TableCell><TableCell className="text-right"><Button size="sm" variant="ghost" disabled={saving} onClick={()=>undo(r.negotiationId)}><Undo2 data-icon="inline-start"/>Deshacer</Button></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>}

<Card><CardHeader><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><CardTitle>Objetivos COBIT 2019</CardTitle><CardDescription>Monitoreo continuo de los {objectives.length} objetivos de gobierno y gestión</CardDescription></div><div className="flex flex-col gap-2 sm:flex-row"><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground"/><Input className="pl-9 sm:w-64" placeholder="Buscar código u objetivo" value={query} onChange={e=>setQuery(e.target.value)}/></div><Select value={domain} onValueChange={v=>setDomain(v??"ALL")}><SelectTrigger className="sm:w-40"><SelectValue placeholder="Dominio"/></SelectTrigger><SelectContent><SelectGroup><SelectItem value="ALL">Todos</SelectItem>{domains.map(d=><SelectItem key={d.code} value={d.code}>{d.code}</SelectItem>)}</SelectGroup></SelectContent></Select></div></div></CardHeader><CardContent className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Código</TableHead><TableHead>Objetivo</TableHead><TableHead>Dominio</TableHead><TableHead>Health score</TableHead><TableHead>Medición</TableHead><TableHead>Prioridad</TableHead><TableHead>Agente</TableHead></TableRow></TableHeader><TableBody>{filtered.map(o=><TableRow key={o.code} className="cursor-pointer" onClick={()=>setSelectedCode(o.code)}><TableCell className="font-mono text-primary">{o.code}</TableCell><TableCell className="min-w-72 font-medium">{o.name}</TableCell><TableCell><Badge variant="outline">{o.domain}</Badge></TableCell><TableCell>{o.score===null?<span className="text-xs text-muted-foreground">sin dato</span>:<div className="flex min-w-36 items-center gap-2"><Progress value={o.score}/><span className="w-8 font-mono text-xs">{o.score}</span>{o.delta!==0&&<span className={`w-8 font-mono text-[10px] ${o.delta>0?"text-success":"text-destructive"}`}>{o.delta>0?"+":""}{o.delta}</span>}</div>}</TableCell><TableCell>{o.measure?<Badge variant="secondary" className="font-mono" title={o.measure.metric}>medido · n={o.measure.sample}</Badge>:<Badge variant="outline" className="text-muted-foreground">línea base</Badge>}</TableCell><TableCell><Badge variant={o.priority==="Alta"?"destructive":o.priority==="Sin dato"?"outline":"secondary"}>{o.priority}</Badge></TableCell><TableCell className="text-muted-foreground">{o.agent}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card>

<Sheet open={!!selected} onOpenChange={o=>!o&&setSelectedCode(null)}><SheetContent className="w-full overflow-y-auto sm:max-w-xl"><SheetHeader><SheetTitle className="font-mono text-primary">{selected?.code} · {selected?.name}</SheetTitle><SheetDescription>Análisis explicable y evolución del objetivo</SheetDescription></SheetHeader>{selected&&<div className="flex flex-col gap-6 px-4 pb-6"><div><p className="status-label text-muted-foreground">Descripción</p><p className="mt-2 leading-relaxed">Asegura que las prácticas, estructuras y flujos de información asociados estén alineados con las metas corporativas y produzcan resultados medibles.</p></div>{selected.history.length>0?<div className="h-56"><HistoryChart data={selected.history}/></div>:<p className="rounded-lg border border-dashed p-3 text-xs text-muted-foreground">Sin historial: la evolución aparecerá cuando haya mediciones en más de un periodo.</p>}{selected.measure?<div className="rounded-lg border border-primary/30 bg-primary/5 p-4"><p className="status-label text-primary">Cómo se mide</p><p className="mt-2 text-sm font-medium">{selected.measure.metric}</p><p className="mt-1 text-sm leading-relaxed text-muted-foreground">{selected.measure.evidence}</p><p className="mt-2 font-mono text-xs text-muted-foreground">score {selected.measure.score} · muestra n={selected.measure.sample}{selected.measure.sample<5&&" · muestra pequeña, interpretar con cautela"}</p></div>:<div className="rounded-lg border border-dashed p-4"><p className="status-label text-muted-foreground">Sin medición operativa</p><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Este objetivo todavía no tiene una métrica definida sobre la capa operativa.{selected.baseScore!==null?` El ${selected.baseScore} que se muestra es su línea base declarada, no una medición.`:" No hay línea base declarada, así que no se muestra ningún número."}</p></div>}{selectedDecision&&<div className="rounded-lg border border-primary/30 bg-primary/5 p-4"><p className="status-label text-primary">Decisión del comité · {selectedDecision.at} · {selectedDecision.decidedBy}</p><p className="mt-2 text-sm font-medium">{selectedDecision.verdict==="approved"?"Aprobada":"Rechazada"} — {selectedDecision.label}</p><p className="mt-1 text-sm leading-relaxed text-muted-foreground">{selectedDecision.impact}</p><p className={`mt-2 font-mono text-xs ${selectedDecision.delta>0?"text-success":"text-destructive"}`}>Health score {selectedDecision.delta>0?"+":""}{selectedDecision.delta}</p></div>}</div>}</SheetContent></Sheet>
</div>}

function DecisionCard({negotiation:n,saving,onDecide}:{negotiation:NegotiationView;saving:boolean;onDecide:(n:NegotiationView,v:Verdict)=>void}){return <article className={`flex flex-col gap-4 rounded-lg border bg-background/50 p-5 ${n.severity==="critical"?"critical-glow":"warning-glow"}`}><header className="flex items-center gap-2"><ShieldAlert className={n.severity==="critical"?"text-destructive":"text-warning"}/><Badge variant="outline" className="font-mono">{n.objective}</Badge><span className="ml-auto truncate text-xs text-muted-foreground">{n.time}</span></header>
<div><p className="status-label text-muted-foreground">Qué ocurrió</p><p className="mt-1 text-sm leading-relaxed">{n.fact}</p></div>
<div><p className="status-label mb-2 text-muted-foreground">La discrepancia</p><div className="flex flex-col gap-2"><div className="rounded-lg border bg-background/60 p-3"><div className="mb-1 flex items-center gap-2"><Badge variant="outline" className="font-mono">{n.initiatorAgent}</Badge><span className="truncate text-xs text-muted-foreground">{n.initiatorName}</span></div><p className="text-sm leading-relaxed">{n.initiatorPosition}</p></div><div className="flex items-center justify-center text-muted-foreground"><ArrowLeftRight className="size-3.5"/></div><div className="rounded-lg border bg-background/60 p-3"><div className="mb-1 flex items-center gap-2"><Badge variant="outline" className="font-mono">{n.counterpartAgent}</Badge><span className="truncate text-xs text-muted-foreground">{n.counterpartName}</span></div><p className="text-sm leading-relaxed">{n.counterpartPosition}</p></div></div></div>
<div className="rounded-lg border border-warning/25 bg-warning/5 p-3"><p className="status-label flex items-center gap-1.5 text-warning"><Scale className="size-3.5"/>Por qué escala · principio {n.principle}</p><p className="mt-1 text-xs leading-relaxed text-muted-foreground">{n.escalationReason}</p></div>
<div className="rounded-lg border border-primary/25 bg-primary/5 p-3"><p className="status-label text-primary">Propuesta que llega al comité</p><p className="mt-1 text-sm leading-relaxed">{n.proposal}</p></div>
<div className="grid gap-3 sm:grid-cols-2"><Consequence title="Si apruebas" tone="success" objective={n.objective} outcome={n.approve}/><Consequence title="Si rechazas" tone="destructive" objective={n.objective} outcome={n.reject}/></div>
<p className="text-[10px] text-muted-foreground">{n.authoredBy==="model"?`Posiciones de los agentes y propuesta redactadas por ${n.authoringModel} desde la evidencia; la regla decidió que escala.`:"Redacción por plantilla de la regla."}</p><div className="grid gap-2 sm:grid-cols-2"><Button disabled={saving} onClick={()=>onDecide(n,"approved")}><Check data-icon="inline-start"/>{n.approve?.label}</Button><Button variant="outline" disabled={saving} onClick={()=>onDecide(n,"rejected")}><X data-icon="inline-start"/>{n.reject?.label}</Button></div></article>}

function Consequence({title,tone,objective,outcome}:{title:string;tone:"success"|"destructive";objective:string;outcome:Outcome|null}){if(!outcome)return null;return <div className="rounded-lg border bg-background/60 p-3"><p className={`status-label ${tone==="success"?"text-success":"text-destructive"}`}>{title}</p><p className="mt-1 text-xs leading-relaxed text-muted-foreground">{outcome.impact}</p>{outcome.delta!==0&&<p className={`mt-2 font-mono text-[11px] ${outcome.delta>0?"text-success":"text-destructive"}`}>{objective} {outcome.delta>0?"+":""}{outcome.delta} health</p>}</div>}
