"use client"
import { useState } from "react"
import { ArrowDownRight,ArrowUpRight,Bell,Check,Search,ShieldAlert,X } from "lucide-react"
import { domains,objectives,alerts as initialAlerts,type Objective,type Domain } from "@/lib/mock-data"
import { Gauge,HistoryChart,MaturityRadar } from "./dashboard-charts"
import { Card,CardContent,CardDescription,CardHeader,CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Progress } from "@/components/ui/progress"
import { Select,SelectContent,SelectGroup,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select"
import { Sheet,SheetContent,SheetDescription,SheetHeader,SheetTitle } from "@/components/ui/sheet"
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from "@/components/ui/table"

export function CommandCenter(){const [feed,setFeed]=useState(initialAlerts);const [query,setQuery]=useState("");const [domain,setDomain]=useState("ALL");const [selected,setSelected]=useState<Objective|null>(null);const filtered=objectives.filter(o=>(domain==="ALL"||o.domain===domain)&&(o.code+o.name).toLowerCase().includes(query.toLowerCase()));return <div className="flex flex-col gap-6">
<section className="grid gap-4 sm:grid-cols-2 md:grid-cols-5">{domains.map(d=><Card key={d.code} className={`overflow-hidden transition-colors ${d.score<70?"critical-glow":d.score<80?"warning-glow":""}`}><CardHeader className="pb-0"><div className="flex items-center justify-between"><Badge variant="outline" className="font-mono">{d.code}</Badge><span className={`flex items-center text-xs ${d.trend>0?"text-success":"text-destructive"}`}>{d.trend>0?<ArrowUpRight/>:<ArrowDownRight/>}{Math.abs(d.trend)}%</span></div><CardDescription className="min-h-10 text-xs leading-relaxed">{d.name}</CardDescription></CardHeader><CardContent className="flex justify-center"><Gauge value={d.score} label={d.code}/></CardContent></Card>)}</section>
<section className="grid gap-4 xl:grid-cols-[minmax(0,1.65fr)_minmax(300px,.75fr)]"><Card><CardHeader><div className="flex items-end justify-between"><div><CardTitle>Madurez por dominio</CardTitle><CardDescription>Actual vs. objetivo del sistema de gobierno</CardDescription></div><div className="hidden gap-4 text-xs sm:flex"><span className="text-primary">● Actual</span><span className="text-muted-foreground">● Objetivo</span></div></div></CardHeader><CardContent className="h-80"><MaturityRadar/></CardContent></Card><Card><CardHeader><div className="flex items-center justify-between"><div><CardTitle>Alertas en vivo</CardTitle><CardDescription>{feed.length} señales requieren atención</CardDescription></div><Bell className="text-warning"/></div></CardHeader><CardContent className="flex max-h-80 flex-col gap-2 overflow-y-auto">{feed.map(a=><article key={a.id} className={`rounded-lg border bg-background/50 p-4 ${a.severity==="critical"?"critical-glow":a.severity==="warning"?"warning-glow":""}`}><div className="flex gap-3"><ShieldAlert className={a.severity==="critical"?"text-destructive":a.severity==="warning"?"text-warning":"text-primary"}/><div className="min-w-0 flex-1"><p className="text-sm leading-relaxed">{a.text}</p><p className="mt-1 text-xs text-muted-foreground">{a.agent} · {a.time}</p></div></div><div className="mt-3 flex gap-2"><Button size="sm" className="flex-1" onClick={()=>setFeed(f=>f.filter(x=>x.id!==a.id))}><Check data-icon="inline-start"/>Aprobar</Button><Button size="icon-sm" variant="ghost" aria-label="Descartar alerta" onClick={()=>setFeed(f=>f.filter(x=>x.id!==a.id))}><X/></Button></div></article>)}</CardContent></Card></section>
<Card><CardHeader><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><CardTitle>Objetivos COBIT 2019</CardTitle><CardDescription>Monitoreo continuo de los 40 objetivos de gobierno y gestión</CardDescription></div><div className="flex flex-col gap-2 sm:flex-row"><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground"/><Input className="pl-9 sm:w-64" placeholder="Buscar código u objetivo" value={query} onChange={e=>setQuery(e.target.value)}/></div><Select value={domain} onValueChange={v=>setDomain(v??"ALL")}><SelectTrigger className="sm:w-40"><SelectValue placeholder="Dominio"/></SelectTrigger><SelectContent><SelectGroup><SelectItem value="ALL">Todos</SelectItem>{domains.map(d=><SelectItem key={d.code} value={d.code}>{d.code}</SelectItem>)}</SelectGroup></SelectContent></Select></div></div></CardHeader><CardContent className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Código</TableHead><TableHead>Objetivo</TableHead><TableHead>Dominio</TableHead><TableHead>Health score</TableHead><TableHead>Prioridad</TableHead><TableHead>Agente</TableHead></TableRow></TableHeader><TableBody>{filtered.map(o=><TableRow key={o.code} className="cursor-pointer" onClick={()=>setSelected(o)}><TableCell className="font-mono text-primary">{o.code}</TableCell><TableCell className="min-w-72 font-medium">{o.name}</TableCell><TableCell><Badge variant="outline">{o.domain}</Badge></TableCell><TableCell><div className="flex min-w-32 items-center gap-2"><Progress value={o.score}/><span className="w-8 font-mono text-xs">{o.score}</span></div></TableCell><TableCell><Badge variant={o.priority==="Alta"?"destructive":"secondary"}>{o.priority}</Badge></TableCell><TableCell className="text-muted-foreground">{o.agent}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
<Sheet open={!!selected} onOpenChange={o=>!o&&setSelected(null)}><SheetContent className="w-full overflow-y-auto sm:max-w-xl"><SheetHeader><SheetTitle className="font-mono text-primary">{selected?.code} · {selected?.name}</SheetTitle><SheetDescription>Análisis explicable y evolución del objetivo</SheetDescription></SheetHeader>{selected&&<div className="flex flex-col gap-6 px-4 pb-6"><div><p className="mb-2 text-xs font-semibold uppercase tracking-wider text-muted-foreground">Descripción</p><p className="leading-relaxed">Asegura que las prácticas, estructuras y flujos de información asociados estén alineados con las metas corporativas y produzcan resultados medibles.</p></div><div className="h-56"><HistoryChart data={selected.history}/></div><div className="rounded-lg border bg-muted/40 p-4"><p className="mb-2 text-xs font-semibold uppercase tracking-wider text-primary">Razonamiento del agente</p><p className="text-sm leading-relaxed text-muted-foreground">Detecté una variación de {100-selected.score}% frente al umbral óptimo. Correlacioné indicadores de riesgo, evidencia de controles y tres eventos operativos. Confianza: 87%. Recomiendo revisión humana del propietario del proceso.</p></div></div>}</SheetContent></Sheet>
</div>}
