"use client"
import { Area, AreaChart, Bar, BarChart, CartesianGrid, PolarAngleAxis, PolarGrid, Radar, RadarChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts"
import { animate, motion, useMotionValue, useTransform } from "motion/react"
import { useEffect } from "react"
import type { Domain } from "@/lib/mock-data"

function CountUp({ value }: { value: number }) {
  const count = useMotionValue(0)
  const rounded = useTransform(count, (latest) => Math.round(latest))
  useEffect(() => {
    const controls = animate(count, value, { duration: 1.15, ease: "easeOut" })
    return controls.stop
  }, [count, value])
  return <motion.span>{rounded}</motion.span>
}

export function Gauge({value,label}:{value:number;label:string}){const r=42,c=2*Math.PI*r; const tone=value>=80?"var(--success)":value>=70?"var(--warning)":"var(--destructive)";return <div className="relative size-28 shrink-0" role="img" aria-label={`${label}: ${value} de 100`}><svg className="size-full -rotate-90" viewBox="0 0 100 100"><circle cx="50" cy="50" r={r} fill="none" stroke="var(--muted)" strokeWidth="5"/><motion.circle cx="50" cy="50" r={r} fill="none" stroke={tone} strokeWidth="5" strokeLinecap="round" strokeDasharray={c} initial={{strokeDashoffset:c}} animate={{strokeDashoffset:c*(1-value/100)}} transition={{duration:1.15,ease:"easeOut"}} style={{filter:`drop-shadow(0 0 5px ${tone})`}}/></svg><div className="absolute inset-0 flex flex-col items-center justify-center"><strong className="font-mono text-3xl font-semibold tracking-tight"><CountUp value={value}/></strong><span className="status-label mt-0.5 text-[9px]">Health</span></div></div>}
export function MaturityRadar(){const data=[{d:"EDM",actual:4.3,target:4.5},{d:"APO",actual:3.1,target:4.2},{d:"BAI",actual:3.7,target:4.1},{d:"DSS",actual:4,target:4.3},{d:"MEA",actual:3.4,target:4.2}];return <ResponsiveContainer width="100%" height="100%"><RadarChart data={data}><PolarGrid stroke="rgb(255 255 255 / 7%)"/><PolarAngleAxis dataKey="d" tick={{fill:"var(--muted-foreground)",fontSize:11,fontFamily:"var(--font-geist-mono)"}}/><Radar name="Objetivo" dataKey="target" stroke="var(--muted-foreground)" strokeWidth={1.5} fill="var(--muted)" fillOpacity={.16}/><Radar name="Actual" dataKey="actual" stroke="var(--primary)" strokeWidth={2} fill="var(--primary)" fillOpacity={.16}/><Tooltip contentStyle={{background:"var(--popover)",border:"1px solid var(--border)",borderRadius:8}}/></RadarChart></ResponsiveContainer>}
export function HistoryChart({data}:{data:number[]}){const points=data.map((v,i)=>({m:["Mar","Abr","May","Jun","Jul","Ago"][i],v}));return <ResponsiveContainer width="100%" height="100%"><AreaChart data={points}><defs><linearGradient id="h" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="var(--primary)" stopOpacity={.35}/><stop offset="1" stopColor="var(--primary)" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="rgb(255 255 255 / 6%)"/><XAxis dataKey="m" axisLine={false} tickLine={false} tick={{fill:"var(--muted-foreground)",fontSize:10,fontFamily:"var(--font-geist-mono)"}}/><YAxis domain={[0,100]} hide/><Area type="monotone" dataKey="v" stroke="var(--primary)" strokeWidth={2} fill="url(#h)"/></AreaChart></ResponsiveContainer>}
const domainColor:Record<Domain,string>={EDM:"var(--domain-edm)",APO:"var(--domain-apo)",BAI:"var(--domain-bai)",DSS:"var(--domain-dss)",MEA:"var(--domain-mea)"}
export function PriorityBars({data}:{data:{code:string;score:number;domain:Domain}[]}){return <ResponsiveContainer width="100%" height={520}><BarChart data={data.slice(0,14)} layout="vertical" margin={{left:8,right:20}}><CartesianGrid horizontal={false} stroke="var(--border)"/><XAxis type="number" domain={[0,100]} tick={{fill:"var(--muted-foreground)",fontSize:10}}/><YAxis type="category" dataKey="code" width={52} tick={{fill:"var(--foreground)",fontFamily:"monospace",fontSize:11}}/><Tooltip cursor={{fill:"var(--muted)"}} contentStyle={{background:"var(--popover)",border:"1px solid var(--border)",borderRadius:8}}/><Bar dataKey="score" radius={[0,4,4,0]} fill="var(--primary)" isAnimationActive/></BarChart></ResponsiveContainer>}
export function Sparkline({data}:{data:number[]}){return <ResponsiveContainer width="100%" height="100%"><AreaChart data={data.map((v,i)=>({i,v}))}><Area type="monotone" dataKey="v" stroke="var(--primary)" fill="var(--primary)" fillOpacity={.1}/></AreaChart></ResponsiveContainer>}
