"use client"
import { useEffect,useMemo,useRef,useState,useTransition } from "react"
import { AnimatePresence,motion } from "motion/react"
import { Activity,AlertTriangle,ArrowLeftRight,BrainCircuit,Check,CircleDot,Cpu,ScanLine,Send,ShieldCheck,Sparkles } from "lucide-react"
import { applyDesignProfile,saveAiAssessment,scanOrganization } from "@/app/actions"
import type { AiSystemView,DesignFactorView } from "@/lib/types"
import { comparePriorities,computePriorities,neutralInputs } from "@/lib/design-engine"
import { CopilotAnswer } from "./copilot-answer"
import { useGovernance } from "./governance-provider"
import { PriorityBars,Sparkline } from "./dashboard-charts"
import { Avatar,AvatarFallback } from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card,CardContent,CardDescription,CardHeader,CardTitle } from "@/components/ui/card"
import { Checkbox } from "@/components/ui/checkbox"
import { Input } from "@/components/ui/input"
import { Select,SelectContent,SelectGroup,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select"
import { Sheet,SheetContent,SheetDescription,SheetHeader,SheetTitle } from "@/components/ui/sheet"
import { Slider } from "@/components/ui/slider"
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from "@/components/ui/table"

export function AgentsView(){const {agents,objectives,negotiations,log,lastEvaluation}=useGovernance();const [selectedCode,setSelectedCode]=useState<string|null>(null);const selected=agents.find(a=>a.code===selectedCode)??null;const mine=selected?negotiations.filter(n=>n.initiatorAgent===selected.code||n.counterpartAgent===selected.code):[];const authoredByModel=negotiations.filter(n=>n.authoredBy==="model").length;
return <div className="flex flex-col gap-6"><div><h2 className="text-2xl font-semibold text-balance">Red multiagente</h2><p className="text-muted-foreground">{agents.length} agentes con mandato propio sobre {objectives.length} objetivos. Las reglas detectan, los agentes argumentan, Nexus aplica el mandato, el comité decide.</p></div>
<section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{agents.map(a=><Card key={a.code} className={`cursor-pointer transition-all hover:-translate-y-0.5 ${a.status==="Alerta"?"critical-glow":""}`} onClick={()=>setSelectedCode(a.code)}><CardHeader><div className="flex items-start justify-between"><Avatar className="size-11"><AvatarFallback className="bg-primary/15 font-mono text-primary">{a.code}</AvatarFallback></Avatar><Badge variant={a.status==="Alerta"?"destructive":"secondary"}><CircleDot className={a.status!=="Activo"?"animate-pulse":""}/>{a.status}</Badge></div><CardTitle>Agente {a.code} — {a.name}</CardTitle><CardDescription>{a.action}</CardDescription></CardHeader><CardContent><div className="mb-3 flex justify-between text-xs"><span className="text-muted-foreground">Objetivos de su dominio</span><span className="font-mono">{a.watched}</span></div><div className="mb-3 flex gap-3 text-xs"><span><span className="font-mono text-warning">{a.escalated}</span> escaladas</span><span><span className="font-mono text-primary">{a.resolved}</span> resueltas</span><span><span className="font-mono text-success">{a.signed}</span> firmadas</span></div><div className="h-16"><Sparkline data={a.activity}/></div><p className="mt-1 text-[10px] text-muted-foreground">Discrepancias levantadas por quincena, últimas 16 semanas</p></CardContent></Card>)}</section>

<Card className="border-primary/30 bg-primary/5"><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle className="flex items-center gap-2"><Cpu className="text-primary"/>Motor Nexus</CardTitle><CardDescription>No es un agente: aplica el mandato a lo que los agentes detectan y decide qué llega al comité. Corre tras cada operación, cada firma y cada cambio de mandato.</CardDescription></div>{lastEvaluation&&<Badge variant="outline" className="whitespace-nowrap font-mono text-[10px]">última corrida {lastEvaluation.ranAt}</Badge>}</div></CardHeader>{lastEvaluation?<CardContent className="grid gap-3 text-sm sm:grid-cols-3 lg:grid-cols-6"><div><p className="status-label text-muted-foreground">Mandato aplicado</p><p className="mt-1 font-medium">{lastEvaluation.mandate}</p><p className="font-mono text-xs text-muted-foreground">apetito {lastEvaluation.riskAppetite.toFixed(1)}/5</p></div><div><p className="status-label text-muted-foreground">Discrepancias</p><p className="mt-1 font-mono text-2xl">{lastEvaluation.negotiations}</p></div><div><p className="status-label text-muted-foreground">Escaladas</p><p className="mt-1 font-mono text-2xl text-warning">{lastEvaluation.escalated}</p></div><div><p className="status-label text-muted-foreground">Resueltas</p><p className="mt-1 font-mono text-2xl text-primary">{lastEvaluation.resolved}</p></div><div><p className="status-label text-muted-foreground">Retiradas</p><p className="mt-1 font-mono text-2xl">{lastEvaluation.retired}</p><p className="text-[10px] text-muted-foreground">el hecho se corrigió</p></div><div><p className="status-label text-muted-foreground">Redactadas por modelo</p><p className="mt-1 font-mono text-2xl">{lastEvaluation.authored}</p><p className="font-mono text-[10px] text-muted-foreground">{lastEvaluation.authoringModel??"sin modelo"} · {lastEvaluation.durationMs} ms</p></div></CardContent>:<CardContent><p className="text-sm text-muted-foreground">Todavía no ha corrido ninguna evaluación.</p></CardContent>}</Card>

<Card><CardHeader><CardTitle>Negociaciones entre agentes</CardTitle><CardDescription>{negotiations.filter(n=>n.outcome==="resolved").length} resueltas entre agentes · {negotiations.filter(n=>n.outcome==="escalated").length} escaladas al comité · {authoredByModel} de {negotiations.length} con posiciones redactadas por el modelo desde la evidencia</CardDescription></CardHeader><CardContent className="grid gap-3 lg:grid-cols-2">{negotiations.map(n=>{const decision=log.find(d=>d.negotiationId===n.id);const waiting=n.outcome==="escalated"&&!decision;return <article key={n.id} className={`rounded-lg border p-4 ${waiting?"warning-glow":"bg-background/60"}`}><div className="mb-3 flex flex-wrap items-center gap-2"><Badge variant="outline" className="font-mono">{n.initiatorAgent}</Badge><ArrowLeftRight className="size-3.5 text-muted-foreground"/><Badge variant="outline" className="font-mono">{n.counterpartAgent}</Badge><Badge variant="secondary" className="font-mono">{n.objective}</Badge><span className="ml-auto text-xs text-muted-foreground">{n.time}</span></div><p className="text-sm leading-relaxed"><span className="font-mono text-xs text-primary">{n.initiatorAgent}</span> {n.initiatorPosition}</p><p className="mt-1.5 text-sm leading-relaxed text-muted-foreground"><span className="font-mono text-xs">{n.counterpartAgent}</span> {n.counterpartPosition}</p>{n.outcome==="resolved"?<p className="mt-3 text-xs leading-relaxed text-primary">Nexus · consenso: {n.resolution} · principio {n.principle}</p>:decision?<p className="mt-3 text-xs leading-relaxed text-success">Escalada y firmada por {decision.decidedBy}: {decision.verdict==="approved"?"aprobada":"rechazada"} — {decision.label}</p>:<p className="mt-3 text-xs leading-relaxed text-warning">Nexus · sin consenso dentro del mandato · principio {n.principle} · esperando firma del comité</p>}<p className="mt-2 text-[10px] text-muted-foreground">{n.authoredBy==="model"?`posiciones y síntesis redactadas por ${n.authoringModel}`:"redacción por plantilla de la regla (sin modelo disponible)"}</p></article>})}</CardContent></Card>

<Sheet open={!!selected} onOpenChange={o=>!o&&setSelectedCode(null)}><SheetContent className="overflow-y-auto sm:max-w-xl"><SheetHeader><SheetTitle>Agente {selected?.code} — {selected?.name}</SheetTitle><SheetDescription>Mandato, actividad y discrepancias en las que participa</SheetDescription></SheetHeader>{selected&&<div className="flex flex-col gap-5 px-4 pb-6"><div className="rounded-lg border border-primary/25 bg-primary/5 p-4"><p className="status-label text-primary">Mandato</p><p className="mt-2 text-sm leading-relaxed">{selected.mandate}</p></div><div className="grid grid-cols-3 gap-3 text-center"><div className="rounded-lg border p-3"><p className="font-mono text-2xl text-warning">{selected.escalated}</p><p className="text-xs text-muted-foreground">escaladas</p></div><div className="rounded-lg border p-3"><p className="font-mono text-2xl text-primary">{selected.resolved}</p><p className="text-xs text-muted-foreground">resueltas</p></div><div className="rounded-lg border p-3"><p className="font-mono text-2xl text-success">{selected.signed}</p><p className="text-xs text-muted-foreground">firmadas</p></div></div><div><p className="status-label mb-2 text-muted-foreground">Discrepancias en las que participa</p>{mine.length===0?<p className="text-sm text-muted-foreground">Ninguna. Las reglas de su dominio no han detectado discrepancias con los datos actuales.</p>:<ul className="flex flex-col gap-2">{mine.map(n=><li key={n.id} className="rounded-lg border bg-background/50 p-3 text-sm"><div className="mb-1 flex items-center gap-2"><Badge variant="outline" className="font-mono">{n.objective}</Badge><Badge variant={n.outcome==="escalated"?"destructive":"secondary"}>{n.outcome==="escalated"?"escalada":"resuelta"}</Badge><span className="ml-auto text-xs text-muted-foreground">{n.time}</span></div><p className="text-muted-foreground">{n.fact}</p></li>)}</ul>}</div></div>}</SheetContent></Sheet></div>}

export function SimulatorView(){const {designFactors,activeProfile,objectives}=useGovernance();const [applying,startApply]=useTransition();const [profileName,setProfileName]=useState("");
const mandate=useMemo(()=>activeProfile?.inputs??neutralInputs(designFactors),[activeProfile,designFactors]);
const [inputs,setInputs]=useState<Record<string,number>>(mandate);
const mandateAppetite=activeProfile?.riskAppetite??3.5;const [appetite,setAppetite]=useState(mandateAppetite);const appetiteChanged=appetite!==mandateAppetite;
const domainOf=useMemo(()=>new Map(objectives.map(o=>[o.code,o.domain])),[objectives]);
const nameOf=useMemo(()=>new Map(objectives.map(o=>[o.code,o.name])),[objectives]);
const ranked=useMemo(()=>computePriorities(designFactors,inputs),[designFactors,inputs]);
const current=useMemo(()=>computePriorities(designFactors,mandate),[designFactors,mandate]);
const diff=useMemo(()=>comparePriorities(current,ranked),[current,ranked]);
const bars=useMemo(()=>ranked.map(p=>({code:p.code,score:p.score,domain:domainOf.get(p.code)!})),[ranked,domainOf]);
function set(id:string,value:number){setInputs(v=>({...v,[id]:value}))}
function setChoice(factor:DesignFactorView,key:string){setInputs(v=>{const next={...v};for(const value of factor.values)next[value.id]=value.key===key?1:0;return next})}
function apply(){const name=profileName.trim()||"Rediseño del comité";startApply(async()=>{await applyDesignProfile(name,inputs,appetite);setProfileName("")})}
return <div className="flex flex-col gap-5">
<div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><h2 className="text-2xl font-semibold">Diseño del sistema de gobierno</h2><p className="text-muted-foreground">Los 10 factores de diseño de COBIT 2019 recalculan la prioridad de los 40 objetivos</p></div>{activeProfile&&<div className="rounded-lg border bg-background/60 px-4 py-2 text-xs"><p className="status-label text-primary">Mandato vigente</p><p className="mt-1">{activeProfile.name} · apetito {activeProfile.riskAppetite.toFixed(1)}/5 · {activeProfile.appliedBy} · {activeProfile.appliedAt}</p></div>}</div>
<div className="grid gap-5 xl:grid-cols-[minmax(0,420px)_1fr]">
<div className="flex max-h-[76vh] flex-col gap-3 overflow-y-auto pr-1"><Card className="border-primary/30"><CardHeader><div className="flex items-center gap-2"><Badge variant="outline" className="font-mono">EDM03</Badge><CardTitle className="text-base">Apetito de riesgo</CardTitle></div><CardDescription className="text-xs">Riesgo residual máximo que el comité tolera. Los agentes escalan lo que lo supere.</CardDescription></CardHeader><CardContent><label className="flex flex-col gap-2"><span className="flex justify-between text-sm"><span>Umbral residual</span><span className="font-mono text-primary">{appetite.toFixed(1)}/5</span></span><Slider min={1} max={5} step={0.5} value={[appetite]} onValueChange={x=>setAppetite(typeof x==="number"?x:x[0])}/></label></CardContent></Card>{designFactors.map(factor=><Card key={factor.code}><CardHeader><div className="flex items-center gap-2"><Badge variant="outline" className="font-mono">{factor.code}</Badge><CardTitle className="text-base">{factor.name}</CardTitle></div><CardDescription className="text-xs">{factor.description}</CardDescription></CardHeader><CardContent className="flex flex-col gap-3">
{factor.input==="rating"&&factor.values.map(v=><label key={v.id} className="flex flex-col gap-2"><span className="flex justify-between text-sm"><span>{v.label}</span><span className="font-mono text-primary">{inputs[v.id]??3}/5</span></span><Slider min={1} max={5} step={1} value={[inputs[v.id]??3]} onValueChange={x=>set(v.id,typeof x==="number"?x:x[0])}/></label>)}
{factor.input==="toggle"&&factor.values.map(v=><label key={v.id} className="flex items-start gap-3 text-sm"><Checkbox checked={(inputs[v.id]??0)>0} onCheckedChange={on=>set(v.id,on===true?1:0)}/><span className="leading-tight text-muted-foreground">{v.label}</span></label>)}
{factor.input==="choice"&&<Select value={factor.values.find(v=>(inputs[v.id]??0)>0)?.key??factor.values[0].key} onValueChange={k=>k&&setChoice(factor,k)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectGroup>{factor.values.map(v=><SelectItem key={v.id} value={v.key}>{v.label}</SelectItem>)}</SelectGroup></SelectContent></Select>}
</CardContent></Card>)}</div>
<div className="flex flex-col gap-4"><Card><CardHeader><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><CardTitle>Priorización resultante</CardTitle><CardDescription>Importancia relativa · 100 = objetivo más prioritario para esta configuración</CardDescription></div><Badge variant={diff.changed>0?"default":"secondary"}><Activity/>{diff.changed>0?`${diff.changed} objetivos cambian de puesto`:"Igual al mandato vigente"}</Badge></div></CardHeader><CardContent>{diff.changed>0&&<div className="mb-4 flex flex-col gap-1 rounded-lg border border-primary/25 bg-primary/5 p-3 text-xs"><p className="status-label text-primary">Mayor movimiento frente al mandato vigente</p>{diff.biggest.map(b=><p key={b.code} className="text-muted-foreground"><span className="font-mono text-primary">{b.code}</span> {nameOf.get(b.code)} <span className={b.delta>0?"text-success":"text-destructive"}>{b.delta>0?`sube ${b.delta}`:`baja ${-b.delta}`} {Math.abs(b.delta)===1?"puesto":"puestos"}</span></p>)}</div>}<AnimatePresence mode="popLayout"><motion.div key={JSON.stringify(bars.slice(0,14))} initial={{opacity:.5,y:6}} animate={{opacity:1,y:0}}><PriorityBars data={bars}/></motion.div></AnimatePresence></CardContent></Card>
<div className="flex flex-col gap-2 sm:flex-row"><Input className="sm:w-56" placeholder="Nombre del diseño" value={profileName} onChange={e=>setProfileName(e.target.value)} disabled={applying}/><Button className="flex-1" disabled={applying||(diff.changed===0&&!appetiteChanged)} onClick={apply}><Sparkles data-icon="inline-start"/>{applying?"Aplicando...":"Aplicar este diseño como mandato"}</Button><Button variant="outline" disabled={applying||(diff.changed===0&&!appetiteChanged)} onClick={()=>{setInputs(mandate);setAppetite(mandateAppetite)}}>Descartar cambios</Button></div>
<p className="text-xs leading-relaxed text-muted-foreground">Los pesos que relacionan cada factor con los 40 objetivos son una calibración propia de este proyecto, no las tablas licenciadas del COBIT 2019 Design Toolkit de ISACA. La estructura del cálculo —suma ponderada y normalización a importancia relativa— sí sigue el modelo de COBIT, y los pesos viven en la tabla <code className="font-mono">design_factor_weights</code> para poder sustituirlos por los oficiales sin tocar el motor.</p></div>
</div></div>}

const suggested=["¿Por qué APO12 está en rojo?","¿Qué decisiones esperan mi firma?","¿Qué sistemas de IA no tienen controles aceptados?"]
type ChatMessage = { role:"user"|"assistant"; text:string }
const greeting:ChatMessage = {role:"assistant",text:"Puedo responder sobre el estado de gobierno registrado: objetivos COBIT, negociaciones entre agentes, decisiones firmadas y el registro de sistemas de IA. ¿Qué quieres revisar?"}

export function CopilotView(){const [messages,setMessages]=useState<ChatMessage[]>([greeting]);const [input,setInput]=useState("");const [streaming,setStreaming]=useState(false);const viewport=useRef<HTMLDivElement>(null);
useEffect(()=>{viewport.current?.scrollTo({top:viewport.current.scrollHeight})},[messages]);
async function send(text=input){
 const question=text.trim()
 if(!question||streaming)return
 const history=[...messages,{role:"user" as const,text:question}]
 setMessages([...history,{role:"assistant",text:""}]);setInput("");setStreaming(true)
 try{
  const response=await fetch("/api/copilot",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages:history.map(m=>({role:m.role,content:m.text}))})})
  if(!response.ok||!response.body)throw new Error((await response.text())||`El copiloto respondió ${response.status}.`)
  const reader=response.body.getReader();const decoder=new TextDecoder()
  for(;;){
   const {done,value}=await reader.read()
   if(done)break
   const chunk=decoder.decode(value,{stream:true})
   setMessages(m=>m.map((entry,i)=>i===m.length-1?{...entry,text:entry.text+chunk}:entry))
  }
 }catch(error){
  const detail=error instanceof Error?error.message:"No se pudo consultar al copiloto."
  setMessages(m=>m.map((entry,i)=>i===m.length-1?{...entry,text:detail}:entry))
 }finally{setStreaming(false)}
}
const waiting=streaming&&messages[messages.length-1]?.text===""
return <Card className="mx-auto flex min-h-[calc(100vh-10rem)] max-w-5xl flex-col"><CardHeader className="border-b"><CardTitle className="flex items-center gap-2"><BrainCircuit className="text-primary"/>Copiloto Nexus</CardTitle><CardDescription>Responde solo con el estado de gobierno registrado en la base de datos</CardDescription><div className="flex flex-wrap gap-2 pt-3">{suggested.map(q=><Button key={q} size="sm" variant="outline" disabled={streaming} onClick={()=>send(q)}>{q}</Button>)}</div></CardHeader>
<CardContent ref={viewport} className="flex flex-1 flex-col gap-4 overflow-y-auto py-6">{messages.map((m,i)=><div key={i} className={`flex ${m.role==="user"?"justify-end":"justify-start"}`}><div className={`max-w-[80%] rounded-xl border px-4 py-3 text-sm leading-relaxed ${m.role==="user"?"whitespace-pre-wrap bg-primary text-primary-foreground":"bg-muted/60"}`}>{m.role==="user"?m.text:<CopilotAnswer text={m.text}/>}</div></div>)}{waiting&&<div className="flex gap-1 text-primary"><span className="animate-bounce">●</span><span className="animate-bounce [animation-delay:120ms]">●</span><span className="animate-bounce [animation-delay:240ms]">●</span></div>}</CardContent>
<div className="flex gap-2 border-t p-4"><Input value={input} onChange={e=>setInput(e.target.value)} disabled={streaming} onKeyDown={e=>{if(e.key==="Enter"&&!e.nativeEvent.isComposing&&e.keyCode!==229)send()}} placeholder="Pregunta sobre objetivos, negociaciones, decisiones o sistemas de IA..."/><Button size="icon" aria-label="Enviar" disabled={streaming||input.trim().length===0} onClick={()=>send()}><Send/></Button></div></Card>}

export function AIGovernanceView(){const {aiSystems}=useGovernance();const [scanning,startScan]=useTransition();const [saving,startSave]=useTransition();const [selectedId,setSelectedId]=useState<number|null>(null);const [accepted,setAccepted]=useState<string[]>([]);const selected=aiSystems.find(s=>s.id===selectedId)??null;
function openSystem(system:AiSystemView){setSelectedId(system.id);setAccepted(system.acceptedControls)}
function toggle(control:string,on:boolean){setAccepted(v=>on?[...new Set([...v,control])]:v.filter(c=>c!==control))}
function save(){if(!selected)return;const id=selected.id;startSave(async()=>{await saveAiAssessment(id,accepted);setSelectedId(null)})}
return <div className="flex flex-col gap-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-2xl font-semibold">Registro de sistemas de IA</h2><p className="text-muted-foreground">Descubrimiento continuo de shadow AI y evaluación de controles</p></div><Button onClick={()=>startScan(async()=>{await scanOrganization()})} disabled={scanning}><ScanLine data-icon="inline-start" className={scanning?"animate-pulse":""}/>{scanning?"Escaneando red...":"Escanear organización"}</Button></div>
{scanning&&<div className="h-1 overflow-hidden rounded bg-muted"><motion.div className="h-full w-1/3 bg-primary" animate={{x:["-100%","300%"]}} transition={{repeat:Infinity,duration:1}}/></div>}
<Card><CardContent className="overflow-x-auto pt-6"><Table><TableHeader><TableRow><TableHead>Sistema</TableHead><TableHead>Área</TableHead><TableHead>Descripción</TableHead><TableHead>Riesgo</TableHead><TableHead>Controles COBIT</TableHead><TableHead>Estado</TableHead></TableRow></TableHeader><TableBody>{aiSystems.map(s=><TableRow key={s.id} className="cursor-pointer" onClick={()=>openSystem(s)}><TableCell className="font-medium">{s.name}</TableCell><TableCell>{s.area}</TableCell><TableCell className="min-w-64 text-muted-foreground">{s.description}</TableCell><TableCell><Badge variant={s.risk==="Alto"?"destructive":"secondary"}>{s.risk}</Badge></TableCell><TableCell><div className="flex gap-1">{s.controls.map(c=><Badge key={c} variant={s.acceptedControls.includes(c)?"default":"outline"} className="font-mono">{s.acceptedControls.includes(c)&&<Check/>}{c}</Badge>)}</div></TableCell><TableCell><Badge variant={s.status==="Aprobado"?"secondary":s.status==="Bloqueado"?"destructive":"outline"}>{s.status}</Badge></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
<Sheet open={!!selected} onOpenChange={o=>!o&&setSelectedId(null)}><SheetContent className="overflow-y-auto sm:max-w-xl"><SheetHeader><SheetTitle>{selected?.name}</SheetTitle><SheetDescription>Evaluación de riesgo y controles recomendados</SheetDescription></SheetHeader>{selected&&<div className="flex flex-col gap-5 px-4 pb-6"><p className="leading-relaxed">{selected.description}. El análisis detectó tratamiento de información corporativa y dependencia de un proveedor sin evaluación formal.</p><div className="rounded-lg border bg-destructive/5 p-4"><p className="mb-2 flex items-center gap-2 font-medium"><AlertTriangle className="text-destructive"/>Justificación de riesgo</p><p className="text-sm text-muted-foreground">Impacto potencial sobre confidencialidad y decisiones automatizadas. Confianza del clasificador: 92%.</p></div><div><p className="font-medium">Controles recomendados</p><p className="mb-3 text-xs text-muted-foreground">Marca los que el comité asume como obligatorios para este sistema.</p>{selected.controls.map(c=><label key={c} className="flex items-center gap-3 border-b py-3"><Checkbox checked={accepted.includes(c)} onCheckedChange={v=>toggle(c,v===true)}/><span className="font-mono text-primary">{c}</span><span className="text-sm text-muted-foreground">Implementar evidencia verificable</span></label>)}</div><p className="text-xs leading-relaxed text-muted-foreground">{accepted.length===0?"Sin controles aceptados el sistema queda Pendiente.":accepted.length===selected.controls.length?"Con todos los controles aceptados el sistema queda Aprobado.":`Con ${accepted.length} de ${selected.controls.length} controles el sistema queda Parcial.`}</p><Button disabled={saving} onClick={save}><ShieldCheck data-icon="inline-start"/>{saving?"Guardando...":"Guardar evaluación"}</Button></div>}</SheetContent></Sheet></div>}
