"use client"
import { useState } from "react"
import { Plus } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card,CardContent,CardDescription,CardHeader,CardTitle } from "@/components/ui/card"
import { Sheet,SheetContent,SheetDescription,SheetHeader,SheetTitle } from "@/components/ui/sheet"
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from "@/components/ui/table"
import type { ControlTestView,ControlView } from "@/lib/types"
import { Feedback,Field,SelectField,TextField } from "./shared"
import { useOperations } from "./use-operations"

const RESULTS=[{value:"Efectivo",label:"Efectivo"},{value:"Parcial",label:"Parcial"},{value:"Inefectivo",label:"Inefectivo"}] as const
const resultVariant=(r:ControlTestView["result"])=>r==="Efectivo"?"secondary":r==="Parcial"?"default":"destructive"

export function ControlsPanel({controls,objectives}:{controls:ControlView[];objectives:{code:string;name:string}[]}){
 const {run,busy,error,last,activity}=useOperations()
 const [selectedCode,setSelectedCode]=useState<string|null>(null)
 const selected=controls.find(c=>c.code===selectedCode)??null
 const [fResult,setFResult]=useState<ControlTestView["result"]>("Efectivo");const [fEvidence,setFEvidence]=useState("");const [fBy,setFBy]=useState("Auditoría Interna")
 const overdue=controls.filter(c=>c.overdue).length;const ineffective=controls.filter(c=>c.lastTest?.result==="Inefectivo").length
 const [defining,setDefining]=useState(false);const [dCode,setDCode]=useState("");const [dName,setDName]=useState("");const [dObjective,setDObjective]=useState(objectives[0]?.code??"");const [dOwner,setDOwner]=useState("");const [dFreq,setDFreq]=useState("30")
 async function define(){if(await run({type:"control.define",payload:{code:dCode,name:dName,objectiveCode:dObjective,owner:dOwner,frequencyDays:Number(dFreq)}})){setDefining(false);setDCode("");setDName("");setDOwner("")}}
 async function test(){if(selected&&await run({type:"control.test",payload:{controlCode:selected.code,result:fResult,evidence:fEvidence,testedBy:fBy}})){setSelectedCode(null);setFEvidence("")}}

 return <div className="flex flex-col gap-4">
  <div className="grid gap-3 sm:grid-cols-3"><Card className={overdue>0?"warning-glow":""}><CardHeader className="pb-2"><CardDescription>Con prueba vencida</CardDescription><CardTitle className="font-mono text-2xl">{overdue}</CardTitle></CardHeader></Card><Card className={ineffective>0?"critical-glow":""}><CardHeader className="pb-2"><CardDescription>Última prueba inefectiva</CardDescription><CardTitle className="font-mono text-2xl">{ineffective}</CardTitle></CardHeader></Card><Card><CardHeader className="pb-2"><CardDescription>Alimenta a</CardDescription><CardTitle className="font-mono text-base text-primary">MEA02 + el objetivo de cada control</CardTitle></CardHeader></Card></div>
  <Card><CardHeader><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><CardTitle>Controles internos</CardTitle><CardDescription>Cada control declara qué objetivo COBIT protege. Su última prueba es lo que ese objetivo mide cuando no tiene métrica propia.</CardDescription></div><Button onClick={()=>setDefining(true)}><Plus data-icon="inline-start"/>Definir control</Button></div><div className="pt-3"><Feedback error={error} last={last} activity={activity}/></div></CardHeader>
   <CardContent className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Control</TableHead><TableHead>Nombre</TableHead><TableHead>Protege</TableHead><TableHead>Responsable</TableHead><TableHead>Frecuencia</TableHead><TableHead>Última prueba</TableHead><TableHead>Resultado</TableHead><TableHead className="text-right">Acción</TableHead></TableRow></TableHeader>
   <TableBody>{controls.map(c=><TableRow key={c.code} className="cursor-pointer" onClick={()=>setSelectedCode(c.code)}><TableCell className="font-mono text-primary">{c.code}</TableCell><TableCell className="min-w-56 font-medium">{c.name}</TableCell><TableCell><Badge variant="outline" className="font-mono" title={c.objectiveName}>{c.objectiveCode}</Badge></TableCell><TableCell className="text-muted-foreground">{c.owner}</TableCell><TableCell className="font-mono text-xs">{c.frequencyDays} d</TableCell><TableCell className="whitespace-nowrap text-xs">{c.lastTest?<span className={c.overdue?"text-destructive":""}>{c.lastTest.testedLabel} · hace {c.daysSinceTest} d{c.overdue&&" · vencida"}</span>:<span className="text-destructive">nunca</span>}</TableCell><TableCell>{c.lastTest?<Badge variant={resultVariant(c.lastTest.result)}>{c.lastTest.result}</Badge>:"—"}</TableCell><TableCell className="text-right"><Button size="sm" variant="outline" onClick={e=>{e.stopPropagation();setSelectedCode(c.code)}}>Probar</Button></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
  {controls.length===0&&<p className="px-1 text-xs text-muted-foreground">Todavía no hay controles definidos. Cada uno que definas y pruebes alimenta al objetivo COBIT que protege.</p>}
  <Sheet open={defining} onOpenChange={o=>!o&&setDefining(false)}><SheetContent className="overflow-y-auto sm:max-w-lg"><SheetHeader><SheetTitle>Definir control</SheetTitle><SheetDescription>Un control es una práctica que se prueba periódicamente. Su resultado se convierte en la medición del objetivo que protege.</SheetDescription></SheetHeader><div className="flex flex-col gap-4 px-4 pb-6"><TextField label="Código" value={dCode} onChange={setDCode} placeholder="01" hint="Se antepone CTL- automáticamente"/><TextField label="Nombre" value={dName} onChange={setDName} placeholder="Aprobación formal de cambios"/><SelectField label="Objetivo COBIT que protege" value={dObjective} onChange={setDObjective} options={objectives.map(o=>({value:o.code,label:`${o.code} · ${o.name}`}))}/><TextField label="Responsable" value={dOwner} onChange={setDOwner} placeholder="Gerencia de Cambios"/><TextField label="Frecuencia de prueba (días)" type="number" value={dFreq} onChange={setDFreq}/><Button disabled={busy||!dCode.trim()||!dName.trim()||!dOwner.trim()} onClick={define}>{busy?"Registrando...":"Definir control"}</Button></div></SheetContent></Sheet>
  <Sheet open={!!selected} onOpenChange={o=>!o&&setSelectedCode(null)}><SheetContent className="overflow-y-auto sm:max-w-lg"><SheetHeader><SheetTitle className="font-mono text-primary">{selected?.code}</SheetTitle><SheetDescription>{selected?.name} · protege {selected?.objectiveCode} ({selected?.objectiveName})</SheetDescription></SheetHeader>
   {selected&&<div className="flex flex-col gap-5 px-4 pb-6"><Field label="Registrar prueba" hint={fResult==="Inefectivo"?"Una prueba inefectiva escala al comité por MEA02.":"El resultado pasa a ser la medición vigente del objetivo."}><SelectField label="Resultado" value={fResult} onChange={setFResult} options={RESULTS}/><TextField label="Evidencia" value={fEvidence} onChange={setFEvidence} placeholder="Ej. Muestra de 12 cambios, 2 sin acta"/><TextField label="Probado por" value={fBy} onChange={setFBy}/><Button disabled={busy||!fEvidence.trim()} onClick={test}>{busy?"Registrando...":"Registrar prueba"}</Button></Field>
   <div><p className="status-label mb-2 text-muted-foreground">Historial</p>{selected.tests.length===0?<p className="text-sm text-muted-foreground">Este control nunca se ha probado.</p>:<ul className="flex flex-col gap-2">{selected.tests.map((t,i)=><li key={i} className="flex items-start gap-3 rounded-lg border bg-background/50 p-3 text-sm"><Badge variant={resultVariant(t.result)}>{t.result}</Badge><div className="min-w-0"><p>{t.evidence}</p><p className="text-xs text-muted-foreground">{t.testedLabel} · {t.testedBy}</p></div></li>)}</ul>}</div></div>}</SheetContent></Sheet>
 </div>
}
