"use client"
import { useState } from "react"
import { Plus } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card,CardContent,CardDescription,CardHeader,CardTitle } from "@/components/ui/card"
import { Sheet,SheetContent,SheetDescription,SheetHeader,SheetTitle } from "@/components/ui/sheet"
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from "@/components/ui/table"
import type { ServiceView,SupplierView } from "@/lib/types"
import { Feedback,Field,SelectField,TextField } from "./shared"
import { useOperations } from "./use-operations"

export function ServicesPanel({services,suppliers}:{services:ServiceView[];suppliers:SupplierView[]}){
 const {run,busy,error,last,activity}=useOperations()
 const [service,setService]=useState<ServiceView|null>(null);const [supplier,setSupplier]=useState<SupplierView|null>(null)
 const [mAvail,setMAvail]=useState("99.9");const [mBreaches,setMBreaches]=useState("0")
 const [eCompliance,setECompliance]=useState("95");const [eFindings,setEFindings]=useState("0");const [eBy,setEBy]=useState("Gerencia de Abastecimiento")
 const critVariant=(c:string)=>c==="Crítico"?"destructive":c==="Alto"?"default":"secondary"
 const CRIT=[{value:"Crítico",label:"Crítico"},{value:"Alto",label:"Alto"},{value:"Medio",label:"Medio"},{value:"Bajo",label:"Bajo"}] as const
 const [newService,setNewService]=useState(false);const [sCode,setSCode]=useState("");const [sName,setSName]=useState("");const [sCrit,setSCrit]=useState<"Crítico"|"Alto"|"Medio"|"Bajo">("Alto");const [sOwner,setSOwner]=useState("");const [sTarget,setSTarget]=useState("99.5");const [sCritMin,setSCritMin]=useState("60");const [sHighMin,setSHighMin]=useState("240")
 const [newSupplier,setNewSupplier]=useState(false);const [pCode,setPCode]=useState("");const [pName,setPName]=useState("");const [pCrit,setPCrit]=useState<"Crítico"|"Alto"|"Medio"|"Bajo">("Alto");const [pService,setPService]=useState("");const [pEnd,setPEnd]=useState("")
 async function registerService(){if(await run({type:"service.register",payload:{code:sCode,name:sName,criticality:sCrit,owner:sOwner,targetAvailability:Number(sTarget),slaCriticalMinutes:Number(sCritMin),slaHighMinutes:Number(sHighMin)}})){setNewService(false);setSCode("");setSName("");setSOwner("")}}
 async function registerSupplier(){if(await run({type:"supplier.register",payload:{code:pCode,name:pName,criticality:pCrit,service:pService,contractEnd:pEnd?new Date(pEnd).toISOString():undefined}})){setNewSupplier(false);setPCode("");setPName("");setPService("")}}
 async function measure(){if(service&&await run({type:"sla.measure",payload:{serviceCode:service.code,measuredAvailability:Number(mAvail),breaches:Number(mBreaches)}}))setService(null)}
 async function evaluate(){if(supplier&&await run({type:"supplier.evaluate",payload:{supplierCode:supplier.code,slaCompliance:Number(eCompliance),findings:Number(eFindings),evaluatedBy:eBy}}))setSupplier(null)}

 return <div className="flex flex-col gap-4"><Feedback error={error} last={last} activity={activity}/>
  <Card><CardHeader><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><CardTitle>Catálogo de servicios</CardTitle><CardDescription>Los servicios de TI que la organización presta. Sin servicios no hay incidentes ni cambios que registrar. La disponibilidad medida alimenta a BAI04 y APO09.</CardDescription></div><Button onClick={()=>setNewService(true)}><Plus data-icon="inline-start"/>Dar de alta servicio</Button></div></CardHeader>
   <CardContent className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Servicio</TableHead><TableHead>Criticidad</TableHead><TableHead>Propietario</TableHead><TableHead>Objetivo</TableHead><TableHead>Último periodo</TableHead><TableHead>Incidentes abiertos</TableHead><TableHead className="text-right">Acción</TableHead></TableRow></TableHeader>
   <TableBody>{services.map(s=><TableRow key={s.code}><TableCell><span className="font-mono text-primary">{s.code}</span> <span className="font-medium">{s.name}</span></TableCell><TableCell><Badge variant={critVariant(s.criticality)}>{s.criticality}</Badge></TableCell><TableCell className="text-muted-foreground">{s.owner}</TableCell><TableCell className="font-mono">{s.targetAvailability}%</TableCell><TableCell className="font-mono text-xs">{s.latestAvailability===null?"—":<span className={s.latestAvailability>=s.targetAvailability?"text-success":"text-destructive"}>{s.latestAvailability.toFixed(2)}% · {s.latestBreaches} incumpl.</span>}</TableCell><TableCell className="font-mono">{s.openIncidents}</TableCell><TableCell className="text-right"><Button size="sm" variant="outline" onClick={()=>{setService(s);setMAvail(String(s.targetAvailability))}}>Medir periodo</Button></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
  <Card><CardHeader><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><CardTitle>Proveedores</CardTitle><CardDescription>Terceros de los que depende la operación. La última evaluación de cada uno alimenta a APO10.</CardDescription></div><Button onClick={()=>setNewSupplier(true)}><Plus data-icon="inline-start"/>Dar de alta proveedor</Button></div></CardHeader>
   <CardContent className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Proveedor</TableHead><TableHead>Criticidad</TableHead><TableHead>Servicio</TableHead><TableHead>Contrato</TableHead><TableHead>Última evaluación</TableHead><TableHead className="text-right">Acción</TableHead></TableRow></TableHeader>
   <TableBody>{suppliers.map(s=><TableRow key={s.code}><TableCell><span className="font-mono text-primary">{s.code}</span> <span className="font-medium">{s.name}</span></TableCell><TableCell><Badge variant={critVariant(s.criticality)}>{s.criticality}</Badge></TableCell><TableCell className="text-muted-foreground">{s.service}</TableCell><TableCell className="text-xs"><span className={s.contractDaysLeft<90?"text-destructive":""}>{s.contractEndLabel} ({s.contractDaysLeft} d)</span></TableCell><TableCell className="font-mono text-xs">{s.latestCompliance===null?"sin evaluar":<span className={s.latestCompliance>=90?"text-success":"text-warning"}>{s.latestCompliance}% · {s.latestFindings} hallazgos · {s.latestEvaluatedLabel}</span>}</TableCell><TableCell className="text-right"><Button size="sm" variant="outline" onClick={()=>setSupplier(s)}>Evaluar</Button></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
  {services.length===0&&<p className="px-1 text-xs text-muted-foreground">Todavía no hay servicios: da de alta el primero para poder registrar incidentes y cambios.</p>}
  <Sheet open={newService} onOpenChange={o=>!o&&setNewService(false)}><SheetContent className="overflow-y-auto sm:max-w-lg"><SheetHeader><SheetTitle>Dar de alta servicio</SheetTitle><SheetDescription>Define el compromiso: disponibilidad objetivo y tiempos de resolución por severidad.</SheetDescription></SheetHeader><div className="flex flex-col gap-4 px-4 pb-6"><TextField label="Código" value={sCode} onChange={setSCode} placeholder="ERP" hint="Se antepone SVC- automáticamente"/><TextField label="Nombre" value={sName} onChange={setSName} placeholder="ERP corporativo"/><SelectField label="Criticidad" value={sCrit} onChange={setSCrit} options={CRIT}/><TextField label="Propietario" value={sOwner} onChange={setSOwner} placeholder="Dirección de Finanzas"/><TextField label="Disponibilidad objetivo (%)" type="number" value={sTarget} onChange={setSTarget}/><div className="grid grid-cols-2 gap-3"><TextField label="SLA severidad crítica (min)" type="number" value={sCritMin} onChange={setSCritMin}/><TextField label="SLA severidad alta (min)" type="number" value={sHighMin} onChange={setSHighMin}/></div><Button disabled={busy||!sCode.trim()||!sName.trim()||!sOwner.trim()} onClick={registerService}>{busy?"Registrando...":"Registrar servicio"}</Button></div></SheetContent></Sheet>
  <Sheet open={newSupplier} onOpenChange={o=>!o&&setNewSupplier(false)}><SheetContent className="overflow-y-auto sm:max-w-lg"><SheetHeader><SheetTitle>Dar de alta proveedor</SheetTitle><SheetDescription>Terceros críticos requieren evaluación periódica (APO10).</SheetDescription></SheetHeader><div className="flex flex-col gap-4 px-4 pb-6"><TextField label="Código" value={pCode} onChange={setPCode} placeholder="CLOUD" hint="Se antepone SUP- automáticamente"/><TextField label="Nombre" value={pName} onChange={setPName}/><SelectField label="Criticidad" value={pCrit} onChange={setPCrit} options={CRIT}/><TextField label="Servicio que presta" value={pService} onChange={setPService} placeholder="Infraestructura como servicio"/><TextField label="Fin de contrato" type="date" value={pEnd} onChange={setPEnd}/><Button disabled={busy||!pCode.trim()||!pName.trim()||!pService.trim()} onClick={registerSupplier}>{busy?"Registrando...":"Registrar proveedor"}</Button></div></SheetContent></Sheet>
  <Sheet open={!!service} onOpenChange={o=>!o&&setService(null)}><SheetContent className="sm:max-w-lg"><SheetHeader><SheetTitle>Medir periodo · {service?.name}</SheetTitle><SheetDescription>Objetivo comprometido: {service?.targetAvailability}%</SheetDescription></SheetHeader><div className="flex flex-col gap-4 px-4 pb-6"><TextField label="Disponibilidad medida (%)" type="number" value={mAvail} onChange={setMAvail}/><TextField label="Incumplimientos en el periodo" type="number" value={mBreaches} onChange={setMBreaches}/><Button disabled={busy} onClick={measure}>{busy?"Registrando...":"Registrar medición"}</Button></div></SheetContent></Sheet>
  <Sheet open={!!supplier} onOpenChange={o=>!o&&setSupplier(null)}><SheetContent className="sm:max-w-lg"><SheetHeader><SheetTitle>Evaluar · {supplier?.name}</SheetTitle><SheetDescription>{supplier?.service}</SheetDescription></SheetHeader><div className="flex flex-col gap-4 px-4 pb-6"><TextField label="Cumplimiento de SLA (%)" type="number" value={eCompliance} onChange={setECompliance}/><TextField label="Hallazgos" type="number" value={eFindings} onChange={setEFindings}/><TextField label="Evaluado por" value={eBy} onChange={setEBy}/><Field label="" hint="La evaluación más reciente es la que cuenta para APO10."><Button disabled={busy} onClick={evaluate}>{busy?"Registrando...":"Registrar evaluación"}</Button></Field></div></SheetContent></Sheet>
 </div>
}
